version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://user:pass@mongodb
    depends_on:
      - mongodb
  mongodb:
      image: mongodb/mongodb-community-server:6.0.5-ubi8
      environment:  
        - MONGO_INITDB_ROOT_USERNAME=user
        - MONGO_INITDB_ROOT_PASSWORD=pass
      # volumes:
      #   - type: bind
      #     source: ./data
      #     target: /data/db