runtime: custom
env: flex

service: backend

env_variables:
    MONGO_URI: projects/$PROJECT_ID/secrets/MY_FORUM_MONGO_URI/versions/latest
    JWT_SECRET: projects/$PROJECT_ID/secrets/MY_FORUM_JWT_SECRET/versions/latest
