steps:
  - name: gcr.io/cloud-builders/npm
    args: [install, --omit=dev]

  - name: gcr.io/cloud-builders/npm
    args: [run, build, --omit=dev]

  - name: gcr.io/cloud-builders/gcloud
    args: [app, deploy]

