steps:
  - name: gcr.io/cloud-builders/gcloud
    # dir: "./backend/"
    args: [app, deploy, ./backend/app.yaml]
    # args: [app, deploy, --image-url=eu.gcr.io/helical-decoder-387010/app-engine-tmp/app/default/ttl-18h:latest]