name: Run Jest e2e tests for backend with MongoDB*
run-name: ${{ github.actor }} ran e2e tests for backend only

on:
  push:
    branches: ["test"]
  pull_requests:
    branches: ["test"]

defaults:
  run:
    working-directory: ./backend/

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: ["4.2", "4.4", "5.0", "6.0"]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Instal dependencies
        run: npm ci

      - name: Run fixtures
        run: npm run fixtures

      - name: Run tests
        env:
          CI: true
          JWT_SECRET: ${{ secrets.JwtSecret }}
          MONGO_URI: http://localhost:27017
        run: npm run test:e2e
