name: Run Jest e2e tests for backend
run-name: ${{ github.actor }} ran e2e tests for backend only

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

defaults:
  run:
    working-directory: ./backend/

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          # cache: 'npm'
          # cache-dependency-path: ./backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          JWT_SECRET: ${{ secrets.JwtSecret }}
          MONGO_URI: ${{ secrets.MongoUri }}
        run: npm run test:e2e
